baseURL       = "https://hintcool.com/"
languageCode  = "en-us"
title         = "The Clothing Manufacturer You Can Trust"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3


  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "We are HintCool Garment, with more than 10 years of professional men's clothing manufacturing experience, products include men's jackets, cotten coats, vests, trousers, shorts and T-shirts."
  # author = "HintCool"
  # Google Analitycs
  # googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/vIsqqJq"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Type"
    placeholder_about_the_project = "Write something here"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "biz"
      title  = "Business"
    [[params.contactForm.projectType]]
      value = "fun"
      title  = "Nothing"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We Are HintCool, The Clothing Manufacturer You Can Trust"
    tagline               = "Fashions Fade, Style is Eternal"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR PRODUCTS"
    subtitle  = "Something exciting is coming your way"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Connect with Us"
    primary_button      = "Accept"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Longshi RD, Jinjiang, Quanzhou, Fujian, China, 362715"
      phone   = "+8619859026662"
      email   = "joey@hintcool.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"


        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/HintCool"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/hintcool"
    
      # Footer Service
      [params.footer.service]
        title       = "We provide:"
        description = "High quality products, competitive price, and fast delivery"
